export class Remittance {

    oid: string;
    ifrId: string;
    pin: string;
    ttNumber: string;
    recipientName: string;
    recipientMobileNo: string;
    senderName: string;
    senderCountry: string;
    applicationDate: string;
    amount: string;
    actualAmountInBdt: string;
    confirmActualAmountInBDT: string;
    servicePointName: string;
    branchName: string;
    status: string;
    exHouseName:string;
    branchExHouseName:string;
    disbursedOn : string;
    photoId: string;
    photoIdType: string;
    photoIdFrontPath: string;
    photoIdBackPath: string;
    photoIdPathFront: string;
    photoIdPathBack: string;
    recipientGender: string;
    recipientEmail: string;
    recipientPhotoPath: any;
    photoPath: any;
    exhouseOid: any;
    branchExHouseOid: string;
    creditedAccount: string;
    debitedAccount: string;
    csbRequestId: string;
    cbsReferenceNo: string;
    traceId: string;
    editableRemarks: string;
    closingRemark: string;
    remarks: string;
    lockedBy: string;
    lockedOn: string;
    lockStatus: string;
    branchOid: string;
    bankOid: string;
    agentOid: string;
    servicePointOid: string;
    serviceTerminalOid: string;
    isApproverRemarks: string;
    approverRemarks: string;
    editedBy: string;
    editedOn: string;
    dataUpdatedBy: string;
    dataUpdatedOn: string;
    updaterActivityTime: string;
    approvedBy: string;
    approvedOn: string;
    approvalActivityTime: string;
    createdBy: string;
    createdOn: string;
    updatedBy: string;
    updatedOn: string;
    elapsedTime:any;
    colorMark:string;
    isPhotoRetakeRequired:string;
    dateOfBirth:any;
}
